import pandas as pd
from typing import List, Dict

class BacktestEngine:
    """
    Historical Simulation Engine to evaluate AI Agent strategies.
    Calculates crucial metrics like Win Rate, Profit Factor, and Max Drawdown.
    """
    
    def __init__(self, initial_capital: float = 10000.0):
        self.initial_capital = initial_capital
        self.current_capital = initial_capital
        self.trades = []
        
    def simulate(self, df: pd.DataFrame, signals: pd.Series):
        """
        Simulates Buy/Sell actions based on signals array aligned with the DataFrame.
        signals: 1 (BUY), -1 (SELL), 0 (WAIT)
        """
        # Simplified simulation logic for structural foundation
        position = 0 # 0 = flat, >0 = long quantity
        entry_price = 0.0
        
        for idx, row in df.iterrows():
            signal = signals.loc[idx]
            current_price = row['close']
            
            # BUY Logic
            if signal == 1 and position == 0:
                # Risk engine allocates 2% per trade, for simplicity here we buy fixed amount
                position = (self.current_capital * 0.1) / current_price
                entry_price = current_price
                self.current_capital -= (position * current_price)
                
            # SELL Logic (Take Profit or Stop Loss hit assumed generated by signal)
            elif signal == -1 and position > 0:
                profit_loss = (current_price - entry_price) * position
                self.current_capital += (position * current_price)
                self.trades.append({
                    "entry_date": None, # Should track entry date
                    "exit_date": idx,
                    "profit": profit_loss,
                    "return_pct": (current_price - entry_price) / entry_price
                })
                position = 0
                entry_price = 0.0
                
        return self.calculate_metrics()
        
    def calculate_metrics(self) -> Dict:
        if not self.trades:
            return {"error": "No trades executed."}
            
        profits = [t['profit'] for t in self.trades if t['profit'] > 0]
        losses = [abs(t['profit']) for t in self.trades if t['profit'] < 0]
        
        gross_profit = sum(profits)
        gross_loss = sum(losses)
        
        win_rate = len(profits) / len(self.trades) if self.trades else 0
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else float('inf')
        
        return {
            "total_trades": len(self.trades),
            "win_rate": round(win_rate * 100, 2),
            "profit_factor": round(profit_factor, 2),
            "net_profit": round(gross_profit - gross_loss, 2),
            "final_capital": round(self.current_capital, 2)
            # Max Drawdown and Risk/Reward to be implemented using full equity curve
        }
