import uuid
from sqlalchemy import Column, String, Float, Boolean, DateTime, ForeignKey, Integer, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.database.session import Base


class PaperAccount(Base):
    """Virtual trading account — no real money involved."""
    __tablename__ = "paper_accounts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String, nullable=False, default="Default Paper Account")
    initial_capital = Column(Float, nullable=False)
    cash_balance = Column(Float, nullable=False)       # Current available cash
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    orders = relationship("PaperOrder", back_populates="account", cascade="all, delete-orphan")
    positions = relationship("PaperPosition", back_populates="account", cascade="all, delete-orphan")


class PaperOrder(Base):
    """
    A virtual BUY/SELL order generated by the AI Decision Engine.
    Status: OPEN → FILLED → CLOSED (TP/SL hit) or CANCELLED
    """
    __tablename__ = "paper_orders"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    account_id = Column(UUID(as_uuid=True), ForeignKey("paper_accounts.id", ondelete="CASCADE"), nullable=False)
    symbol = Column(String, nullable=False, index=True)
    action = Column(String, nullable=False)           # BUY | SELL
    quantity = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit = Column(Float, nullable=True)
    ai_confidence = Column(Float, nullable=False)
    ai_risk_level = Column(String, nullable=False)
    status = Column(String, default="OPEN", index=True)  # OPEN | FILLED | WIN | LOSS | CANCELLED
    fill_price = Column(Float, nullable=True)
    close_price = Column(Float, nullable=True)
    profit_loss = Column(Float, nullable=True)         # In currency units
    profit_loss_pct = Column(Float, nullable=True)     # As percentage
    opened_at = Column(DateTime(timezone=True), server_default=func.now())
    closed_at = Column(DateTime(timezone=True), nullable=True)
    ai_evidence = Column(JSONB, nullable=True)

    account = relationship("PaperAccount", back_populates="orders")

    __table_args__ = (
        Index("ix_paper_orders_symbol_status", "symbol", "status"),
    )


class PaperPosition(Base):
    """Current open positions in the virtual portfolio."""
    __tablename__ = "paper_positions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    account_id = Column(UUID(as_uuid=True), ForeignKey("paper_accounts.id", ondelete="CASCADE"), nullable=False)
    symbol = Column(String, nullable=False)
    quantity = Column(Float, nullable=False)
    average_entry_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=True)
    unrealized_pnl = Column(Float, nullable=True)
    unrealized_pnl_pct = Column(Float, nullable=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    account = relationship("PaperAccount", back_populates="positions")

    __table_args__ = (
        Index("ix_paper_positions_account_symbol", "account_id", "symbol", unique=True),
    )


class PerformanceReport(Base):
    """Daily snapshot of Paper Trading performance metrics."""
    __tablename__ = "performance_reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    account_id = Column(UUID(as_uuid=True), ForeignKey("paper_accounts.id", ondelete="CASCADE"), nullable=False)
    report_date = Column(DateTime(timezone=True), server_default=func.now())
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)
    profit_factor = Column(Float, default=0.0)
    max_drawdown = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, default=0.0)
    roi = Column(Float, default=0.0)                   # Return on Initial Capital
    false_signal_rate = Column(Float, default=0.0)
    risk_violation_count = Column(Integer, default=0)
    portfolio_value = Column(Float, default=0.0)       # Cash + open positions value
    metrics_snapshot = Column(JSONB, nullable=True)    # Full metrics JSON

    __table_args__ = (
        Index("ix_performance_reports_account_date", "account_id", "report_date"),
    )
