import pandas as pd
import pandas_ta as ta

class TechnicalIndicators:
    """
    Calculates technical indicators required by the AI Multi-Agent System.
    Uses pandas-ta for robust and fast computation.
    """
    
    @staticmethod
    def add_all_indicators(df: pd.DataFrame) -> pd.DataFrame:
        """
        Appends MA, RSI, MACD, and Bollinger Bands to the DataFrame.
        """
        # Trend Indicators
        df.ta.sma(length=20, append=True)
        df.ta.sma(length=50, append=True)
        
        # Momentum Indicators
        df.ta.rsi(length=14, append=True)
        
        # MACD (Trend + Momentum)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        
        # Volatility (Bollinger Bands)
        df.ta.bbands(length=20, std=2, append=True)
        
        # Clean up any NaNs generated by rolling windows
        df.dropna(inplace=True)
        
        return df
